# Generated by Django 4.1.3 on 2024-03-21 20:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_remove_article_likes_article_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="title",
        ),
    ]
