# Generated by Django 4.1.3 on 2024-03-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_remove_article_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="title",
            field=models.CharField(default="Default title", max_length=255),
        ),
    ]
